server:
  port: 9082

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}
  pulsar:
    service-url: ${PULSAR_HOST:pulsar://localhost:6650}

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8761/eureka}

messaging:
  provider: ${MESSAGING_PROVIDER:kafka}
  destination:
    user: ${MESSAGING_DESTINATION_USER:user}
    test: ${MESSAGING_DESTINATION_TEST:test}
  kafka:
    client-id: ${KAFKA_CLIENT_ID:user-service}
    topic: ${KAFKA_TOPIC:user}
    group-id: ${KAFKA_GROUP_ID:user-service}
    max-poll-records: ${KAFKA_MAX_POLL_RECORDS:1}
  kinesis:
    stream-name: ${KINESIS_STREAM_NAME:user}
    region: ${KINESIS_REGION:us-east-1}
    endpoint-override: ${ENDPOINT_OVERRIDE:http://localhost:4566}
    async-native: ${KINESIS_ASYNC:true}
    initial-position: TRIM_HORIZON
  pulsar:
    subscription-name: ${PULSAR_SUBSCRIPTION_NAME:user-service}

security:
  enabled: ${SECURITY_ENABLED:false}
  firebase:
    enabled: ${SECURITY_FIREBASE_ENABLED:false}
    api:
      key: ${FIREBASE_API_KEY:}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 30000
  public:
    url: "/auth/v1/**"
  max:
    attempts: ${MAX_ATTEMPTS:3}

cache:
  enabled: ${CACHE_ENABLED:true}
  provider: ${CACHE_PROVIDER:memcached}
  memcached:
    host: ${MEMCACHED_HOST:localhost}
    port: ${MEMCACHED_PORT:11211}

common:
  id-generator: ${ID_GENERATOR:ulid_id}

auth:
  service:
    name: user-service
    base-url: auth/v1
    login-attempt-url: /login-attempt

service:
  general:
    protocol: http://

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    software.amazon.kinesis: DEBUG
    software.amazon.kinesis.coordinator: DEBUG
    software.amazon.kinesis.retrieval: DEBUG