server:
  port: 9082
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}

enable:
  kafka: ${ENABLE_KAFKA:false}

eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8761/eureka}

security:
  enabled: ${SECURITY_ENABLED:false}

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG