server:
  port: 9082
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}
  data:
    redis:
      port: ${REDIS_PORT:6379}
      host: ${REDIS_HOST:localhost}

messaging:
  provider: ${MESSAGING_PROVIDER:kinesis}
  kafka:
    client-id: ${KAFKA_CLIENT_ID:user-service}
    topic: ${KAFKA_TOPIC:user}
    group-id: ${KAFKA_GROUP_ID:user-service}
    max-poll-records: ${KAFKA_MAX_POLL_RECORDS:1}
  kinesis:
    stream-name: ${KINESIS_STREAM_NAME:user}
    region: ${KINESIS_REGION:us-east-1}
    endpoint-override: ${ENDPOINT_OVERRIDE:http://localhost:4566}
    async-native: ${KINESIS_ASYNC:false}



eureka:
  client:
    service-url:
      defaultZone: ${SERVER_DISCOVERY:http://localhost:8761/eureka}

jwt:
  secret: ${JWT_SECRET}
  expiration: 300000

security:
  enabled: ${SECURITY_ENABLED:false}
  jwt:
    secret: ${JWT_SECRET}
    expiration: 300000
  public:
    url: "/auth/v1/**"
  internal:
    api:
      key: ${SECURITY_INTERNAL_API_KEY:e8Jh1Ejk2gFv4nKz6Yf8WvLtBqZo0v+z0lLh9cPeqvU=}
  max:
    attempts: ${MAX_ATTEMPTS:3}

auth:
  service:
    name: user-service
    base-url: auth/v1
    login-attempt-url: /login-attempt

service:
  general:
    protocol: http://

cache:
  enabled: ${CACHE_ENABLED:true}
  provider: ${CACHE_PROVIDER:memcached}

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG